backend:
  build: ./backend
  environment:
    - PORT=${PORT_APP_INTERNAL}
  expose:
    - ${PORT_APP_EXTERNAL}
  ports:
    - "${PORT_APP_EXTERNAL}:${PORT_APP_INTERNAL}"
  links:
    - nats
    - mongo

mongo:
  image: mvertes/alpine-mongo
  ports:
    - "27017:27017"

nats:
  image: nats
  ports:
    - "4222:4222"

