api:
  build: .
  environment:
    - PORT=${PORT_APP_INTERNAL}
  ports:
    - "8080:8080"
  links:
    - mongo

mongo:
  image: mvertes/alpine-mongo
  volumes:
    - ./containers/db/mongo/:/data/db
  ports:
    - "27017:27017"
